jobs:
  nightly:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-package: jdk+fx
        java-version: '20'
    - continue-on-error: true
      name: Build Linux and Mac releases with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: runtimeZipOthers -PprojectVersion=nightly
    - continue-on-error: true
      name: Build Windows release with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: runtimeZipWindows -PprojectVersion=nightly
    - continue-on-error: true
      name: Create Build Info file
      run: 'echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")"
        > build/image/build_info.txt

        '
    - continue-on-error: true
      name: Add build artifacts to nightly release
      uses: pyTooling/Actions/releaser@main
      with:
        files: 'build/image/*.zip

          build/image/build_info.txt

          '
        rm: false
        tag: nightly
        token: ${{ secrets.GITHUB_TOKEN }}
name: Nightly Release
on:
  repository_dispatch:
    types: trigger-ga___nightly.yml
